### ISSUE TITLE
NullPointerException when dialog.show()

### ISSUE THREAD

**Issue by nowfalsalahudeen** [salehyarahmadi/FileAndFolderPicker#3]
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at ir.androidexception.filepicker.dialog.SingleFilePickerDialog.setupDirectoriesListRecyclerView(SingleFilePickerDialog.java:92)
        at ir.androidexception.filepicker.dialog.SingleFilePickerDialog.onCreate(SingleFilePickerDialog.java:71)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:554)
        at android.app.Dialog.show(Dialog.java:394)
        at dev.nowfal.parseserverlearn.ui.aac.fragments.createFragment$onCreateView$3.onClick(createFragment.kt:105)
        at android.view.View.performClick(View.java:7869)
        at android.widget.TextView.performClick(TextView.java:14958)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
        at android.view.View.performClickInternal(View.java:7838)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29362)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by hernaezanthony** [comment]
For Android 10, try to add the line below on your manifest inside Application. 

android:requestLegacyExternalStorage="true"
